name: TPMS Simulation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TPMS simulation
        run: python main.py

      - name: Run visualization (no GUI needed)
        run: python visualizations/plot_logs.py
            
      - name: Upload TPMS Graph
        uses: actions/upload-artifact@v4
        with:
          name: TPMS_Graphs
          path: tpms_graphs/tire_data_overview.png
